### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by JohnDoe3005** [EverythingSmartHome/fingerprint-mqtt#10]
Hi,

I'm using a Wemos D1 mini with a R503 Fingerprint sensor. The wiring seems to be correct and mqtt is working too.
I can learn new fingers but everytime i put my finger on the sensor i get this output

```
Found fingerprint sensor!
Connecting.......
Connected, IP address: 192.168.7.172
Attempting MQTT connection...connected
Image taken
Image converted
Unknown error
Communication error

```
It seems to happen in this part of the sketch

```
  // OK converted!
  p = finger.fingerFastSearch();
  if (p == FINGERPRINT_OK) {
    Serial.println("Found a print match!");
    lastID = finger.fingerID;
    lastConfidenceScore = finger.confidence;
    return p;
  } else if (p == FINGERPRINT_PACKETRECIEVEERR) {
    Serial.println("Communication error");
    return p;
  } else if (p == FINGERPRINT_NOTFOUND) {
    Serial.println("Did not find a match");
    return p;
  } else {
    Serial.println("Unknown error");
    return p;
  }

```
Any idea how to solve the problem? I tired it with 2 different R503 and two different Wemos D1 mini 

My wiring is

Red + White > 3,3V
Black > Ground
Yellow > D6
Green > D5
Blue > not connected

**Comment by EverythingSmartHome** [comment]
Hello, with this sensor, can you try changing the line:

`p = finger.fingerFastSearch();`

To this:

`p = finger.fingerSearch();`

**Comment by JohnDoe3005** [comment]
working fine now !
Thanks for the super fast solution 👍
