### ISSUE TITLE
Reboot regulary

### ISSUE THREAD

**Issue by orrionis** [EverythingSmartHome/fingerprint-mqtt#25]
Hi 
First thanks for your great work.

In my case, all work, learning deleting, matched...
i can open my nuki lock or unlock with him

but regulary  my wemos reboot and i have this message

`23:17:26.679 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
23:17:26.679 -> 
23:17:26.679 -> Exception (0):
23:17:26.679 -> epc1=0x40209144 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
23:17:26.679 -> 
23:17:26.679 -> >>>stack>>>
23:17:26.679 -> 
23:17:26.679 -> ctx: sys
23:17:26.713 -> sp: 3fffebe0 end: 3fffffb0 offset: 0190
23:17:26.713 -> 3fffed70:  00000025 00000000 00000001 3fffee90  
23:17:26.713 -> 3fffed80:  3ffeb069 3ffecea0 3ffeb08e 00000030  
23:17:26.713 -> 3fffed90:  00001770 000002ee 00001000 40100d06  
23:17:26.746 -> 3fffeda0:  0000001a 3ffedf00 00000020 c0036005  
23:17:26.746 -> 3fffedb0:  00000000 00000001 0000000c 401008c4  
23:17:26.746 -> 3fffedc0:  00000020 3ffef804 3ffea3af 3ffedaf8  
23:17:26.746 -> 3fffedd0:  4022423d 3fffee90 3ffedf00 00000022  
23:17:26.779 -> 3fffede0:  3fffc200 40100800 3fffc258 4000050c  
.......................23:18:25.855 -> 3ffffe10:  3ffefe14 3ffef1fc 3ffef1f0 40217a98  
23:18:25.855 -> 3ffffe20:  00000000 000002ad 3ffeeb98 4020496c  
23:18:25.891 -> 3ffffe30:  00000001 00000025 00000023 00000001  
23:18:25.891 -> 3ffffe40:  3ffefe14 3fff0854 00000020 00000161  
23:18:25.891 -> 3ffffe50:  00000160 3ffefe04 3ffeebec 40204c91  
23:18:25.891 -> 3ffffe60:  3ffefe14 3ffe916c 0054a991 00000000  
23:18:25.924 -> 3ffffe70:  40106361 0054aaec 3ffeecdc 00000000  
23:18:25.924 -> 3ffffe80:  3ffee5e0 3ffeecdc 3ffe85dc 3ffeecdc  
23:18:25.924 -> 3ffffe90:  00000008 3ffffef0 40206190 3fffefb0  
23:18:25.924 -> 3ffffea0:  3ffeecdc 00000008 00000001 402062e5  
23:18:25.957 -> 3ffffeb0:  40204312 3ffeeb58 00000003 40204312  
23:18:25.957 -> 3ffffec0:  000003e8 3ffeeaec 3ffeeb58 402090ec  
23:18:25.957 -> 3ffffed0:  00000005 00000000 3ffe85dc 3ffeed04  
23:18:25.957 -> 3ffffee0:  3ffeeb58 3ffeeaec 3ffeeb58 402045ea  
23:18:25.992 -> 3ffffef0:  ffffef01 0007ffff 00010000 4020397a  
23:18:25.992 -> 3fffff00:  00000001 3ffeeaec 3ffeeaec 40202c3a  
23:18:25.992 -> 3fffff10:  00000000 00003caf 072b020c 00462a60  
23:18:25.992 -> 3fffff20:  3ffe8945 3ffeeaec 0000002b 3ffeeaec  
23:18:26.025 -> 3fffff30:  00000000 00004512 7d01a3d7 004fdd61  
23:18:26.025 -> 3fffff40:  3ffeea48 3ffeeaec 3ffeecd8 40201202  
23:18:26.025 -> 3fffff50:  00000000 3ffeeaec 3ffeecd8 40202440  
23:18:26.058 -> 3fffff60:  00000000 00000000 00000000 00000000  
23:18:26.058 -> 3fffff70:  40106361 0054a28a 3ffeecdc 00000000  
23:18:26.058 -> 3fffff80:  00000000 3ffeecdc 3ffe85dc 3ffeecdc  
23:18:26.058 -> 3fffff90:  3fffdad0 3ffeed04 40206190 3ffeed04  
23:18:26.093 -> 3fffffa0:  3fffdad0 00000000 3ffeecd8 3ffeed04  
23:18:26.093 -> <<<stack<<<
23:18:26.093 -> 
23:18:26.093 -> --------------- CUT HERE FOR EXCEPTION DECODER ---------------
`

what is the problem, how i can fix it . Thanks

**Comment by unseemlycoder** [comment]
Hey @orrionis 
Exception(0) indicates an Illegal instruction. Have you made any modifications to you code? or added a pull-up or pull-down resistor to the board? Issue with watchdog timer logic?

It would be great if you can specify your fingerprint sensor model as well, thanks!
> Exception (0): 23:17:26.679

**Comment by orrionis** [comment]
only modification it was, ssid password....
No resistor
my sensor model is FPM10A

[https://fr.aliexpress.com/item/1005001537603966.html?spm=a2g0n.productlist.0.0.32ebBCWBBCWBsa&browser_id=5988b0db96b241c8ab11cd44490b5455&aff_trace_key=20e6fda71044400a8352532ed8f7f79b-1671574950997-08755-_99MQHV&aff_platform=msite&m_page_id=krqzhaisyzwcaviv185a840adae1ced0c37912b99b&gclid=&pdp_npi=2%40dis%21EUR%218.68%216.16%21%21%21%21%21%4021038edf16735650877775251e5447%2112000016508768750%21sea&curPageLogUid=8gJNAAfdGshf&isseo=y&algo_pvid=fff80935-0345-4907-9fc3-2d3661748ebe](url)

**Comment by orrionis** [comment]
Fixed IT

i downgrade the esp8266 library form born manager
