### ISSUE TITLE
MQTT - learning

### ISSUE THREAD

**Issue by agoralive** [EverythingSmartHome/fingerprint-mqtt#8]
What is the mosquitto_pub message to start learning a new fingerprint?

**Comment by agoralive** [comment]
As a follow up on this question.....

If I send 1 or 2 as a payload to fingerprint/mode/learning, how do I verify that the esp is in learning mode? Because it does not 

How long will it stay in Learning mode? Until finger is enrolled?

It reads my finger just fine, but no fingers have been enrolled yet, so always not matched, is published to MQTT

**Comment by EverythingSmartHome** [comment]
If you subscribe to the STATE topic (/fingerprint/mode/status) then this is where it will tell you instructions for enrolling a print as it is happening. Hope that helps!

**Comment by agoralive** [comment]
YES - that helped a lot..... THANK YOU
